### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by PoonamZ** [taigw/brats17#8]
@taigw while running the train.py I am facing the IOError. Please can you suggest the solution.

Traceback (most recent call last):

  File "<ipython-input-1-e727364173f2>", line 1, in <module>
    runfile('/home/ujjwal/brats17-master/train.py', wdir='/home/ujjwal/brats17-master')

  File "/home/ujjwal/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "/home/ujjwal/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)

  File "/home/ujjwal/brats17-master/train.py", line 121, in <module>
    config_file = str(sys.argv[1])

IndexError: list index out of range

**Comment by taigw** [comment]
@PoonamZ  Is that because you didn't provide arguments when running train.py?

You should provide a configure file as the argument, for example:

python train.py config17/train_wt_ax.txt

**Comment by PoonamZ** [comment]
@taigw  Thank you.

I am facing with the different problem now. Please suggest me the solution. 

python train.py config17/train_wt_ax.txt
data data_root /home/ujjwal/Desktop/ALL_TRIES/brats17-master_NIFTYNET/data_root/Brats17TrainingData /home/ujjwal/Desktop/ALL_TRIES/brats17-master_NIFTYNET/data_root/Brats17TrainingData
data data_names config17/train_names_all.txt config17/train_names_all.txt
data modality_postfix [flair, t1, t1ce, t2] ['flair', 't1', 't1ce', 't2']
data label_postfix seg seg
data file_postfix nii.gz nii.gz
data with_ground_truth True True
data batch_size 5 5
data data_shape [19, 144, 144, 4] [19, 144, 144, 4]
data label_shape [11, 144, 144, 1] [11, 144, 144, 1]
data label_convert_source [0, 1, 2, 4] [0, 1, 2, 4]
data label_convert_target [0, 1, 1, 1] [0, 1, 1, 1]
data batch_slice_direction axial axial
data train_with_roi_patch False False
data label_roi_mask  None
data roi_patch_margin  None
network net_type MSNet MSNet
network net_name MSNet_WT32 MSNet_WT32
network downsample_twice True True
network class_num 2 2
training learning_rate 1e-3 0.001
training decay 1e-7 1e-07
training maximal_iteration 20000 20000
training snapshot_iteration 5000 5000
training start_iteration 0 0
training test_iteration 100 100
training test_step 10 10
training model_pre_trained  None
training model_save_prefix model17/msnet_wt32 model17/msnet_wt32
size of predicty: Tensor("MSNet_WT32/final_pred/conv:0", shape=(5, 11, 144, 144, 2), dtype=float32)
2018-05-24 10:06:52.473231: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-05-24 10:06:52.473255: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-05-24 10:06:52.473260: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-05-24 10:06:52.473263: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-05-24 10:06:52.473267: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "train.py", line 124, in <module>
    train(config_file)
  File "train.py", line 83, in train
    dataloader.load_data()
  File "/home/ujjwal/Desktop/ALL_TRIES/brats17-master_NIFTYNET/util/data_loader.py", line 122, in load_data
    label = crop_ND_volume_with_bounding_box(label, bbmin, bbmax)
  File "/home/ujjwal/Desktop/ALL_TRIES/brats17-master_NIFTYNET/util/data_process.py", line 124, in crop_ND_volume_with_bounding_box
    dim = len(volume.shape)
AttributeError: 'tuple' object has no attribute 'shape'

**Comment by taigw** [comment]
@PoonamZ Have you checked out the latest code? in util/data_loader.py, line 121 should be:

label, _ = self.__load_one_volume(self.patient_names[i], self.label_postfix)
