### ISSUE TITLE
Train:MemoryError occuried

### ISSUE THREAD

**Issue by cb632482135qq** [taigw/brats17#9]
My computer is:

windows 10
GTX1060 6G
16G DDR4 2400Mhz

When I run the" python train.py train_wt_ax.txt" , i meet this problem:

Traceback (most recent call last):
  File "D:\TF\brats17-master\train.py", line 123, in <module>
    train(config_file)
  File "D:\TF\brats17-master\train.py", line 82, in train
    dataloader.load_data()
  File "D:\TF\brats17-master\util\data_loader.py", line 112, in load_data
    volume = itensity_normalize_one_volume(volume)
  File "D:\TF\brats17-master\util\data_process.py", line 95, in itensity_normalize_one_volume
    out = (volume - mean)/std
MemoryError

At the same time, I found that my memory utilization is close to 100% from the Task Manager.

Please tell me whether i can get some solutions to this problems. Any help will be appreciated sincerely!

**Comment by taigw** [comment]
@cb632482135qq  Unfortunately, the current implementation requires loading all the training images into the memory at the beginning. You may consider to use a machine with a larger memory or use the IO in NiftyNet to avoid the memory error.
